#!/usr/bin/env bash
# A Bash Script that transfers a file from the client to a server.

if [ $# -lt 4 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  file_path=$1
  server_ip=$2
  username=$3
  ssh_key=$4
  
  # Use SCP to transfer the file to the user's home directory on the server
  scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~"
fi
