#!/usr/bin/env bash
# Manages 'manage_my_process'

if [ $# -gt 0 ]; then
    if [ "$1" == "start" ]; then
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process started"
    elif [ "$1" == "stop" ]; then
        echo "manage_my_process stopped"
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        else
            echo "Error: PID file not found."
            exit 1
        fi
    elif [ "$1" == "restart" ]; then
        if [ -f /var/run/my_process.pid ]; then
            kill "$(cat /var/run/my_process.pid)"
            rm -f /var/run/my_process.pid
        else
            echo "Error: PID file not found."
            exit 1
        fi
        ./manage_my_process &
        echo "$!" > /var/run/my_process.pid
        echo "manage_my_process restarted"
    else
        echo "Usage: manage_my_process {start|stop|restart}"
    fi
else
    echo "Usage: manage_my_process {start|stop|restart}"
fi
