#!/usr/bin/env bash
# Manage my process

if [ $# -eq 0 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

if [ "$1" == "start" ]; then
    ./manage_my_process &
    echo "$!" > /var/run/my_process.pid
    echo "manage_my_process started"
elif [ "$1" == "stop" ]; then
    if [ -f "/var/run/my_process.pid" ]; then
        pid=$(cat /var/run/my_process.pid)
        kill "$pid"
        rm -f /var/run/my_process.pid
        echo "manage_my_process stopped"
    else
        echo "manage_my_process is not running"
    fi
elif [ "$1" == "restart" ]; then
    "$0" stop
    "$0" start
    echo "manage_my_process restarted"
else
    echo "Usage: $0 {start|stop|restart}"
fi
