#!/usr/bin/env bash
# Show my Bash PID
# where only the part of the name after the first dash is displayed

find . -maxdepth 1 -type f -name "*-*" ! -name ".*" -print0 | while IFS= read -r -d '' file; do
  name=$(basename "$file" | cut -d '-' -f 2)
  echo "$name"

  grep -H "bash" "$file"
done
