#!/bin/bash

# This script displays the content of the current directory in a list format,
# showing only the part of the name after the first dash.

for file in *; do
  if [[ "$file" == -* ]]; then
    continue
  fi
  echo "$file" | cut -d '-' -f 2
done
