#!/usr/bin/env bash
# write a Bash script that displays lines containing the bash word, thus allowing you to easily get the PID of your Bash process.

find . -maxdepth 1 -type f -name "*-*" ! -name ".*" | while IFS= read -r file; do
  name=$(basename "$file" | cut -d '-' -f 2)
  echo "$name"

  grep -H "bash" "$file"
done
